### ISSUE TITLE
Blockchain indexation

### ISSUE THREAD

**Issue by fabianPas** [obsidianproject/Blockexplorer#13]
As to make up a balance for the user of the application, we should be able to index the blockchain. We could write up a custom implementation. But the projects below are explained in [this codeproject](https://www.codeproject.com/Articles/819567/NBitcoin-Indexer-A-scalable-and-fault-tolerant-blo) article. 

I think it's deemed best to discuss the valid solutions here, before approaching an implementation.

Resources:
https://github.com/MetacoSA/NBitcoin.Indexer
https://github.com/stratisproject/NStratis.AzureIndexer

**Comment by netsfx** [comment]
done
