### ISSUE TITLE
Display a list with the top 100 addresses sorted by value

### ISSUE THREAD

**Issue by fabianPas** [obsidianproject/Blockexplorer#3]
As an Obsidian user I would like to see a list of the current top 100 addresses sorted by value as to get an idea of the spread of the value of ODN. 

Acceptance criteria:

* A user can access the list from a menu.
* The list displays the value and link to the Obsidian address
* The list is limited to a certain number of addresses (default 100)

Nice to have 
* The list is cached and updated after a certain interval

**Comment by netsfx** [comment]
done
