### ISSUE TITLE
Expose getinfo and getstakinginfo on the api.

### ISSUE THREAD

**Issue by netsfx** [obsidianproject/Blockexplorer#4]
As a website owner (e.g. CryptoCompare, a Community Site), I want to easily access data about the Obsidian blockchain. For example, the output of the rpc commands getinfo, getstakinginfo.

Acceptance Criteria/Implementation notes:

- Expose getinfo and getstakinginfo on ApiController using the same caching mechanism as MoneySupplyJson as a JSON object.
- Document all calls on ApiController in the readme.md or a newly created api.md.

Example:
http://obsidianblockchain2.westeurope.cloudapp.azure.com/api/moneysupplyjson

**Comment by fabianPas** [comment]
I propose to remove the json suffix from the API call routes. As the default response of the API is JSON. If we want to support multiple data formats, we could include a query parameter like ?[otherResponseType]=true (e.g. ?csv=true)

**Comment by jacobzlogar** [comment]
https://codeplanet.io/principles-good-restful-api-design/, the url is fine imo

**Comment by fabianPas** [comment]
I suggest a change like this to preven the controller from clocking up for methods per format:

```
[HttpGet]
public async Task<ActionResult> MoneySupply(ResponseFormat format = ResponseFormat.Json)
{
	try
	{
		var info = await _apiService.GetInfo();
		if (info == null || !string.IsNullOrWhiteSpace(info.Errors))
			return StatusCode(StatusCodes.Status500InternalServerError);

        if (format == ResponseFormat.String)
            return Content(Convert.ToInt32(info.MoneySupply).ToString());

        return Json(new { moneySupply = Convert.ToInt32(info.MoneySupply) });
	}
	catch (Exception)
	{
		return StatusCode(StatusCodes.Status500InternalServerError);
	}
}
```

This makes it easy to specify returns when another response is possible, but is still DRY.

**Comment by netsfx** [comment]
Also, when we get json from the rpc call anyway, we could just forward the whole json string we get. But I guess, I want to stick to going over a model object also in that case.
So for Jacob: just try implementing it as the original ticket says, only remove the json  suffix. from the name of the action method.

**Comment by jacobzlogar** [comment]
`/api/getinfo`
