### ISSUE TITLE
Improved display of the minting/mining transaction

### ISSUE THREAD

**Issue by netsfx** [obsidianproject/Blockexplorer#5]
As a user, I'd like to see an intuitive display of all transactions. The minting transaction is not displayed properly so far, which should be changed.

Investigation needed: Check also the mining transactions (till block 12500)

Acceptance criteria:
- Staking rewards should be shown as 'Minted Coins' not 'Mined Coins'
- The target ODN address of the minting should be shown.
- Mining tx should be shows correctly respectively

Example:
http://obsidianblockchain2.westeurope.cloudapp.azure.com/transaction/8fff6e74f9c10bc8ebbe2a39b096b2b2a9e6d9e94ec5bd16a1dd08a3f2bbba18

**Comment by fabianPas** [comment]
Do we have an example of a mined and staked transaction that contain an amount of ODN? As the transaction in the current example does not contain ODN transferred.

**Comment by netsfx** [comment]
you mean so that fees are > 0?

**Comment by fabianPas** [comment]
Is this a correct stake, but is the staked amount display incorrectly?
