### ISSUE TITLE
The pay-to-address-transaction display is broken/confusing.

### ISSUE THREAD

**Issue by netsfx** [obsidianproject/Blockexplorer#6]
As a user, I'd like to see an intuitive display of all transactions. The pay-to-address-transactions transaction are not displayed properly so far, which should be changed.

Acceptance criteria:

- Addresses are partly missing
- Display fees correctly
- Find out how/if the 20 ODN reward should be displayed
- The user probably wants to know how much, from, to and what the fees were. The UI should make this clear.
Example:
http://obsidianblockchain2.westeurope.cloudapp.azure.com/transaction/13c7af2f929f959fcd3df2444fbc5b6494fe38bdd9aa3bf99a5294b9a1e3b82d

**Comment by fabianPas** [comment]
In the example the receiving address is displayed twice. Is this expected behaviour? As it seems a bit odd.

Also the receiving and sending part says 'none'. What is to make of that?

**Comment by netsfx** [comment]
The example given is the defect that needs to be fixed, not how it should be! Fixing this is the task of this ticket.
